# Generated by Django 3.2.5 on 2021-08-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birthdate', models.DateField(blank=True, default=users.models.return_min_age)),
                ('start_date', models.DateField(default=users.models.return_date_time_now)),
                ('end_date', models.DateField(default=users.models.return_date_time_weeks)),
                ('details', models.TextField(default='blank')),
                ('location', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Comoxo'), (2, 'Conga')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Not Approved'), (1, 'Approved')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Horrible'), (2, 'Unsatisfied'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Not Approved'), (1, 'Approved')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Comoxo'), (2, 'Conga')], default=0)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
