# Generated by Django 3.2.5 on 2021-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_reviews_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
