# Generated by Django 3.2.5 on 2021-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableField_Conga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('field_title', models.CharField(default='title', max_length=255)),
                ('field_content', models.TextField()),
                ('field_img', models.ImageField(default='default.jpg', upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bedroom', max_length=255)),
                ('desc', models.CharField(default='Blank', max_length=255)),
                ('floor', models.IntegerField(default=0)),
                ('roomsq', models.IntegerField(default=19)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Occupied'), (2, 'Maintenance')], default=1)),
                ('pic', models.ImageField(default='default.jpg', upload_to='rooms')),
            ],
        ),
    ]
