# Generated by Django 3.2.5 on 2021-08-28 16:31

import comoxo_farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Fruit'), (1, 'Vegetable'), (2, 'Flower'), (3, 'Others')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EditableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('field_title', models.CharField(default='title', max_length=255)),
                ('field_content', models.TextField()),
                ('field_img', models.ImageField(default='default.jpg', upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='default_task.jpg', upload_to='tasks')),
                ('start_date', models.DateTimeField(default=comoxo_farm.models.return_date_time_now)),
                ('end_date', models.DateTimeField(default=comoxo_farm.models.return_date_time)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('pic', models.ImageField(default='default_post.jpg', upload_to='team')),
            ],
        ),
    ]
